openapi: 3.0.3
info:
  title: Swagger Instituto C.A.A.D - OpenAPI 3.0
  description: Contrato de Software control de Instituto C.A.A.D
  termsOfService: http://swagger.io/terms/
  contact:
    email: lucholal57@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8081/api/v3
tags:
  - name: user
    description: Operaciones con Usuarios

paths:  
  /users/user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDTO'
  
    get:
      tags:
        - user
      summary: Get all users
      description: ''
      operationId: getAllUsers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResponseDTO'
        '404':
          description: Bad request
        

components:
  schemas:
    
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: theUser
        username:
          type: string
          example: John
        email:
          type: string
          format: email
          example: john@email.com
        password:
          type: string
          example: '12345'
        userStatus:
          type: boolean
          description: User Status
          format: int32
          example: 1
      required:
        - name
        - username
        - password
        - userStatus

    UserListDTO:
       type: array
       items:
        $ref: '#/components/schemas/UserDTO'
        
        
    UserListResponseDTO:
       type: object
       properties:
        users:
          type: array
          items:
            $ref: "#/components/schemas/UserDTO"
        
      
    UserResponseDTO:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/UserDTO"


    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string


  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserDTO'

  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
